# Dockerfile
# FROM hothamandcheese/oracle-18.4.0-xe
# reference: https://hub.docker.com/r/quillbuilduser/oracle-18-xe
FROM quillbuilduser/oracle-18-xe

# COPY init.sql /docker-entrypoint-initdb.d/
# ADD script.sh /docker-entrypoint-initdb.d/